import { z } from "zod";

export const ProjectContextSchema = z.object({
  document: z.string().describe("The highly detailed project context markdown document generated by the AI."),
});

export type ProjectContextResult = z.infer<typeof ProjectContextSchema>;
